### ISSUE TITLE
DDD

### ISSUE THREAD

**Issue by evan-hwang** [quick-starters/quick-starters#1]

**Comment by jongmin92** [comment]
https://www.slideshare.net/baejjae93/rich-domain-model

**Comment by jongmin92** [comment]
https://www.youtube.com/watch?v=dJ5C4qRqAgA&ab_channel=%EC%9A%B0%EC%95%84%ED%95%9CTech

**Comment by jongmin92** [comment]
http://www.yes24.com/Product/Goods/93384475
