### ISSUE TITLE
마이크로서비스

### ISSUE THREAD

**Issue by jongmin92** [quick-starters/quick-starters#37]

**Comment by evan-hwang** [comment]
- [Spring Cloud를 이용한 MSA 인프런 강의](https://www.inflearn.com/course/%EC%8A%A4%ED%94%84%EB%A7%81-%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C-%EB%A7%88%EC%9D%B4%ED%81%AC%EB%A1%9C%EC%84%9C%EB%B9%84%EC%8A%A4#reviews)

**Comment by jongmin92** [comment]
- Book: [도메인 주도 설계로 시작하는 마이크로서비스 개발 (핵심 개념과 패턴, 설계, 구현으로 배우는 DDD와 MSA)](http://www.yes24.com/Product/Goods/98880996)

**Comment by jongmin92** [comment]
- Book: [마이크로서비스 도입, 이렇게 한다 (기업의 유연성과 확장성을 높이는 마이크로서비스 마이그레이션 패턴과 현장 사례)](http://www.yes24.com/Product/Goods/96804929)
