### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by evan-hwang** [quick-starters/quick-starters#8]
기본적인 개념, Docker에 띄워서 사용해보기, SpringBoot에 연동해서 사용해보기

**Comment by jongmin92** [comment]
PubSub 사용해보기

**Comment by jongmin92** [comment]
스터디 주제로 선정되어 아래 repo에서 진행
- https://github.com/quick-starters/redis-study
- https://github.com/quick-starters/redis-book
